version: '3.5'

services:

  repository:
    hostname: repository
    container_name: repository
    restart: always
    image: postgres
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    read_only: false
    security_opt:
      - no-new-privileges:true

  # template:
  #   hostname: template
  #   container_name: template
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - repository

networks:
  template:
  repository:
    driver: bridge